server:
  port: 9001
  servlet:
    context-path: /api
spring:
  application:
    name: umbrella-sharing

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://8.129.20.24:3306/umbrella_sharing?tinyInt1isBit=false&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://172.17.0.1:3306/umbrella_sharing?tinyInt1isBit=false&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
#    host: 8.129.20.24
    port: 6379
    database: 1
    password: yong520...
    host: 172.17.0.1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: status
      logic-delete-value: 2
      logic-not-delete-value: 0

#支付
alipay:
  app-id: 2021000117648729
  domain: http://localhost
  private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCUIJWlNpvNlQLNx/2C9o5gUTy0C2T5NcYHatrYbLPL8DEzSAhJFZSC70JrDozPIOUJEQSffoFtdlcOQKLArNv0kit2mpJRDSUuuKwry0Yl2trgPnsKrmkZrDvNe+3fVWxiS5VXzuP0m5QMu0Uyiw4OeDetkumn09UPNJiiPo9zLl0UaJSHynN6mLzC6NQUWAeEsJ7V1qbuNa4/n34FdcO9doBTY0xr2/D4RTnUx+zHogUlT654VmmxANPyubUMWrYK8SbENrHGtxfDJ5Mgl8MELgcnftAI05yB23KaDX33toyH5Tn0cyDDKxW/Sdba8AFJwIxg5hWc2MYj6ggaKPzLAgMBAAECggEBAI+YdvlOUwOcrLcoZM4MjkE4/4vab+xXAL44DCc6WaIeGtQHxGB1Fx9HKi/2TvKMhPuhD8Y+MOIYkpQyfJQj/qa8/H1hou4HvD/qrp1V1Y7k9sHkUAsuwJwup1qwBQ04FnXDp+cTnVCHcaJV+OLigqHsUK1nejND24t+BWljFFUm4XrkhqzzUSXqwqnNsXosyvHepPp0jZaK76VfMvvYPVhx/KPVA1WQ6zcCAtWStaIQhEpKLuBOX8tvccph/bEeQMPSHH9SD9u5667V5sA5m6PzOq8OzocQtN89xyi3stzoW2CpbGgh1TkVkMQNTTBbC+WyVAbu9NO6ZctKv/a+AgECgYEA6ITDDSHMere28dFboMoJr9iuC7ELyaLqtUxrq7vmWuKA+12ovEXOBdp1xfUFqnB9v6lj8LSXbrSUfA+j4p6SO+jGnacx8gjSBm6e35JpzhVsF1s7CweY/7wC4gRxpFhmhbN4Jsjni9neoaSBjDytzdknLKww/zJVhtpTL4H48cECgYEAoxYT3Y785kTjmHnsYRTl/azXfxKStan3keACvbmM27E7jA9+m6V7LaKZuXC/tzlY4wI8tnQFpAXa8GtMVRFUzsavifY6iaB9F//9SqbawcStqntc+LQPSa961GoYXL0Z/5rZj1X5e+J4NMFBZWY/ghuuZpVIGXvXrrxUggkZ+YsCgYEAyTgTQCsOtOiFxpFCNUyCw43FWNLXe6Ckc072IsFSITbBHkc4Pe4+06vxneVkCNKe0B18IpN2NVTK5u32CqjlrjjMoSROwcFGWFCk5p/jNngteaz21J23lyCSchwcaHgkCPJ+OTpFvy5FTyd5AO6GDo0tLKi7Ii3h+/i2YnedA0ECgYB+BUdgg2dlQIJmhoBkHFQEjBURenanrilCLcmwdbsk4HVVK3v4Jg1jHCyRoVBj8wp+kHH9wvXA401lTmRzr6rLBbkLcJuXUc6YRxWhJAISjTptbFpRTEIr/E976Gfe8bkvTKclHZhlZIDisxsnkbUtgtpnJp/KIWpu+dSLjyDlNQKBgQDUNiB85Fz9Zhd1n2vFWTJ0hFoKdyTccQHP5davDhElXDDEcfK7TmZhxG1mwRn9MsPUgYNaw0deDlKQihnNWGEcoSJ4wdzCQMifPWjsnsttYsuk0i2tyJ5r9PAfGY866+yS+NI2D4uQwS2nKIJpWfDmd86c0Qya1JRJcPRxHgelYg==
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzERIuxSuUNW6LtZFUoQOVXFIzUmPwBtQhHedhgv3PlQgrf9KVFT7CzuTzlRluIu+tzm2LckBjNt0tPNK8Gs/prLMxxXmuTtdWzk7bA+GoglIazEHV3ANzi9nRFKNjeEEwDNGOWF62ciFeIZ/dIFiOUDMIH31bQgUVt+k+8iSCKN/3YygfPKFUd9XJIRt/MU/OmiPCYdTvkBaFUARu9sda8ryUSnU7SiyLYzyUdmv4ayxMUx8ygpmnPsZFi6vz6T2PNTq+6gU+LTTf3FTgXzvJLGOxBvLTkXNW9CAfgWgNiSXJtYwYSP/4DDZM04yZNZ+8wIlRVkFfOXr6EOu6/laQIDAQAB
  server-url: https://openapi.alipaydev.com/gateway.do